# @package _global_

# Top-level Hydra configuration for oncotarget-lite
defaults:
  - dataset: depmap
  - prep: base
  - model: logreg
  - eval: base
  - ablation: base
  - _self_

# Global settings
seed: 42
debug: false
output_dir: "results"

# Experiment tracking
mlflow:
  experiment_name: "oncotarget-lite"
  tracking_uri: "file://./mlruns"
  artifact_location: null

# Parallelization
n_jobs: -1
verbose: 1

# Hydra configuration
hydra:
  run:
    dir: ${output_dir}/runs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${output_dir}/sweeps/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}