name: histopath-mil
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  
  # Core ML dependencies
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=11.8
  
  # Scientific computing
  - numpy=1.24.3
  - scipy=1.11.2
  - pandas=2.0.3
  - scikit-learn=1.3.0
  
  # Image processing
  - opencv=4.8.1
  - pillow=10.0.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  
  # System dependencies for OpenSlide
  - openslide
  
  # Development tools
  - black
  - flake8
  - mypy
  - pytest
  - pre-commit
  
  # Jupyter for notebooks
  - jupyter
  - ipykernel
  
  # Pip dependencies not available in conda
  - pip:
    - pytorch-lightning==2.1.0
    - timm==0.9.7
    - hydra-core==1.3.2
    - mlflow==2.7.1
    - albumentations==1.3.1
    - shap==0.42.1
    - captum==0.6.0
    - pytorch-grad-cam==1.4.8
    - streamlit==1.25.0
    - fastapi==0.103.1
    - uvicorn[standard]==0.23.2
    - openslide-python==1.3.0
    - tifffile==2023.7.10
    - h5py==3.9.0
    - pyarrow==13.0.0
    - plotly==5.15.0
    - rich==13.5.2
    - click==8.1.7
    - tqdm==4.65.0