version: 2

sources:
  - name: public_cdm
    description: "Synthetic OMOP CDM data for public demonstration"
    tables:
      - name: person
        description: "Demographic information for persons"
        columns:
          - name: person_id
            description: "Unique identifier for each person"
            tests:
              - unique
              - not_null

      - name: visit_occurrence  
        description: "Visit events for persons"
        columns:
          - name: visit_occurrence_id
            description: "Unique identifier for each visit"
            tests:
              - unique
              - not_null
          - name: person_id
            description: "Foreign key to person"
            tests:
              - not_null

      - name: condition_occurrence
        description: "Condition diagnoses for persons"
        columns:
          - name: condition_occurrence_id
            description: "Unique identifier for each condition"
            tests:
              - unique
              - not_null
          - name: person_id
            description: "Foreign key to person"
            tests:
              - not_null

      - name: measurement
        description: "Laboratory and clinical measurements"
        columns:
          - name: measurement_id
            description: "Unique identifier for each measurement"
            tests:
              - unique
              - not_null
          - name: person_id
            description: "Foreign key to person"
            tests:
              - not_null

models:
  - name: staging_person
    description: "Cleaned and enriched person demographics"
    columns:
      - name: person_id
        description: "Unique identifier for each person"
        tests:
          - unique
          - not_null
      - name: age_years
        description: "Calculated age in years"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 120

  - name: staging_visit_occurrence
    description: "Cleaned and enriched visit data with quality flags"
    columns:
      - name: visit_occurrence_id
        description: "Unique identifier for each visit"
        tests:
          - unique
          - not_null
      - name: length_of_stay_days
        description: "Calculated length of stay"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 365

  - name: mart_patient_summary
    description: "Comprehensive patient summary for analytics"
    columns:
      - name: person_id
        description: "Unique identifier for each person"
        tests:
          - unique
          - not_null
      - name: complexity_score
        description: "Patient complexity heuristic score"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000