version: 1
disable_existing_loggers: false

formatters:
  json_scrubbed:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s %(pathname)s %(lineno)d"
  structured_scrubbed:
    class: clinical_platform.logging_utils.PHIFilterFormatter
    format: "%(asctime)s [%(levelname)8s] %(name)s: %(message)s (%(filename)s:%(lineno)d)"

filters:
  phi_filter_strict:
    class: clinical_platform.logging_utils.PHIFilter
    scrub_values: true
    read_only_mode: true

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: structured_scrubbed
    filters: [phi_filter_strict]
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json_scrubbed
    filters: [phi_filter_strict]
    filename: logs/clinical_platform_readonly.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  clinical_platform:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  uvicorn:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]