version: "3.9"
services:
  minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    container_name: cdp-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./data/minio:/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.0
    container_name: cdp-mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns
    ports:
      - "5000:5000"
    volumes:
      - ./data/mlruns:/mlruns
      - ./data/mlflow.db:/mlflow.db

  api:
    build: .
    container_name: cdp-api
    command: uvicorn clinical_platform.api.main:app --host 0.0.0.0 --port 8000
    env_file: .env.example
    environment:
      - ENV=local
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "8000:8000"
    depends_on:
      - minio
      - mlflow
    volumes:
      - ./:/app

  ui:
    build: .
    container_name: cdp-ui
    command: streamlit run src/clinical_platform/ui/dashboard.py --server.port 8501 --server.address 0.0.0.0
    env_file: .env.example
    environment:
      - ENV=local
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "8501:8501"
    depends_on:
      - api
      - minio
    volumes:
      - ./:/app

