site_name: Clinical Data Platform
site_url: https://altalanta.github.io/clinical-data-platform/
repo_url: https://github.com/altalanta/clinical-data-platform
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
